/** Same taxonomy as CLIENT_USER holidays modal (HOLIDAY_CATEGORIES) + Hebrew national keys used in catalog */
window.ADMIN_HOLIDAY_CATEGORIES = {
    "17th of Tammuz": "יהדות",
    "Asarah B'Tevet (Tenth of Tevet)": "יהדות",
    "Fast of Esther": "יהדות",
    "Gedaliah Fast": "יהדות",
    "Sigd": "יהדות",
    "חנוכה": "יהדות",
    "יום כיפור": "יהדות",
    "ל״ג בעומר": "יהדות",
    "מימונה": "יהדות",
    "סוכות": "יהדות",
    "ערב יום כיפור": "יהדות",
    "ערב סוכות": "יהדות",
    "ערב פורים": "יהדות",
    "ערב פסח": "יהדות",
    "ערב ראש השנה": "יהדות",
    "ערב שבועות": "יהדות",
    "ערב תשעה באב": "יהדות",
    "פורים": "יהדות",
    "פסח": "יהדות",
    "ראש השנה": "יהדות",
    "שבועות": "יהדות",
    "שמחת תורה": "יהדות",
    "תשעה באב": "יהדות",
    "Al Isra' wal Miraj": "אסלאם",
    "Al Isra' wal Miraj (tentative)": "אסלאם",
    "Ashura": "אסלאם",
    "Ashura (tentative)": "אסלאם",
    "Lailat al-Qadr": "אסלאם",
    "יום הולדת הנביא": "אסלאם",
    "יום ראשון של כפות התמרים": "אסלאם",
    "ליילאת אל מיראז'": "אסלאם",
    "ערב יום הולדת הנביא": "אסלאם",
    "ערב ראש השנה המוסלמי": "אסלאם",
    "ערב עיד אל-אדחא": "אסלאם",
    "ערב עיד אל-פיטר": "אסלאם",
    "עיד אל-אדחא": "אסלאם",
    "עיד אל-פיטר": "אסלאם",
    "ראש השנה המוסלמי": "אסלאם",
    "רמדאן": "אסלאם",
    "Eid al-Khader": "דרוזים",
    "Eid al-Khader Eve": "דרוזים",
    "Feast of Prophet Sabalan": "דרוזים",
    "Feast of Prophet Sabalan Eve": "דרוזים",
    "Prophet Shuaib's Feast": "דרוזים",
    "Prophet Shuaib's Feast Eve": "דרוזים",
    "Prophet Shuaib's Feast Holiday": "דרוזים",
    "All Saints' Day": "נצרות",
    "All Souls' Day": "נצרות",
    "Armenian Feast of the Annunciation": "נצרות",
    "Armenian/Orthodox Ascension Day": "נצרות",
    "Armenian/Orthodox Ascension Eve": "נצרות",
    "Armenian/Orthodox Holy Saturday": "נצרות",
    "Armenian/Orthodox Maundy Thursday": "נצרות",
    "Armenian/Orthodox Pentecost": "נצרות",
    "Armenian/Orthodox Pentecost Eve": "נצרות",
    "Armenian/Orthodox Pentecost Monday": "נצרות",
    "Ascension Day": "נצרות",
    "Assumption of Mary": "נצרות",
    "Catholic/Protestant Ascension Day": "נצרות",
    "Catholic/Protestant Ascension Eve": "נצרות",
    "Catholic/Protestant Boxing Day": "נצרות",
    "Catholic/Protestant Epiphany": "נצרות",
    "Catholic/Protestant Epiphany Eve": "נצרות",
    "Catholic/Protestant Feast of the Annunciation": "נצרות",
    "Catholic/Protestant Holy Saturday": "נצרות",
    "Catholic/Protestant Maundy Thursday": "נצרות",
    "Catholic/Protestant Pentecost": "נצרות",
    "Catholic/Protestant Pentecost Eve": "נצרות",
    "Catholic/Protestant Pentecost Monday": "נצרות",
    "Corpus Christi": "נצרות",
    "Epiphany": "נצרות",
    "Feast of Our Lady of Guadalupe": "נצרות",
    "Feast of St Francis of Assisi": "נצרות",
    "Feast of the Immaculate Conception": "נצרות",
    "First Sunday of Advent": "נצרות",
    "Holy Saturday": "נצרות",
    "Maundy Thursday": "נצרות",
    "Orthodox Epiphany Day": "נצרות",
    "Orthodox Epiphany Eve": "נצרות",
    "Orthodox Feast of the Annunciation": "נצרות",
    "Orthodox New Year": "נצרות",
    "Orthodox New Year's Eve": "נצרות",
    "Pentecost": "נצרות",
    "Shrove Tuesday/Mardi Gras": "נצרות",
    "Trinity Sunday": "נצרות",
    "Whit Monday": "נצרות",
    "חג המולד": "נצרות",
    "יום רביעי של האפר": "נצרות",
    "יום שישי הטוב": "נצרות",
    "ערב חג המולד": "נצרות",
    "פסחא": "נצרות",
    "Aliyah Day School Observance": "ממלכתי וכללי",
    "Herzl's Death Anniversary": "ממלכתי וכללי",
    "International Women's Day": "ממלכתי וכללי",
    "Jerusalem Day": "ממלכתי וכללי",
    "May Day": "ממלכתי וכללי",
    "New Year's Eve": "ממלכתי וכללי",
    "St. David's Day": "ממלכתי וכללי",
    "St. Patrick's Day": "ממלכתי וכללי",
    "Victory Day over Nazi Germany": "ממלכתי וכללי",
    "Yom HaAtzmaut": "ממלכתי וכללי",
    "Yom HaShoah": "ממלכתי וכללי",
    "Yom HaZikaron": "ממלכתי וכללי",
    "First Day of School Year": "ממלכתי וכללי",
    "יום הזיכרון": "ממלכתי וכללי",
    "יום העצמאות": "ממלכתי וכללי",
    "יום השואה": "ממלכתי וכללי",
    "ראש השנה (אזרחי)": "ממלכתי וכללי",
    "Holocaust Remembrance Day": "ממלכתי וכללי",
    "Memorial Day": "ממלכתי וכללי",
    "Independence Day": "ממלכתי וכללי"
};
